import type { Metadata } from "next";
import { site } from "@/content/site";

export const BASE_URL = `https://${site.domain}`;

/** Absolute URL for a site-relative path. Schema.org wants absolute URLs. */
export function absoluteUrl(path = "/"): string {
  if (path.startsWith("http")) return path;
  return `${BASE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

export type Crumb = { name: string; href: string };

/**
 * The Person node.
 *
 * One definition, referenced by @id everywhere else, so an Article's author and
 * the site's publisher are the same entity rather than three lookalike copies.
 */
export const PERSON_ID = `${BASE_URL}/#person`;
export const WEBSITE_ID = `${BASE_URL}/#website`;

export function personSchema() {
  return {
    "@type": "Person",
    "@id": PERSON_ID,
    name: site.name,
    alternateName: site.shortName,
    url: BASE_URL,
    email: site.email,
    jobTitle: site.role,
    description: site.statement,
    image: absoluteUrl("/images/profile.png"),
    address: {
      "@type": "PostalAddress",
      addressLocality: "Cyberjaya",
      addressRegion: "Selangor",
      addressCountry: "MY",
    },
    knowsAbout: [
      "Production management systems",
      "Operations software",
      "Full-stack web development",
      "Next.js",
      "TypeScript",
      "Python",
      "FastAPI",
      "LLM application development",
      "Document processing",
      "PostgreSQL",
      "Technical SEO",
      "Structured data",
    ],
    sameAs: [site.links.github, site.links.linkedin, site.links.twitter],
  };
}

export function websiteSchema() {
  return {
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    url: BASE_URL,
    name: site.name,
    description: site.statement,
    inLanguage: "en-MY",
    publisher: { "@id": PERSON_ID },
  };
}

export function breadcrumbSchema(crumbs: Crumb[]) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: absoluteUrl(c.href),
    })),
  };
}

/** Wraps one or more nodes in a single @graph document. */
export function graph(...nodes: Record<string, unknown>[]) {
  return {
    "@context": "https://schema.org",
    "@graph": nodes,
  };
}

/**
 * The default share image, generated by `src/app/opengraph-image.tsx`.
 *
 * Referenced explicitly rather than relied on implicitly: a route that defines
 * its own `openGraph` object replaces the parent's instead of merging into it,
 * so `locale` and `images` silently disappear from every child route unless
 * they are set again. This helper is what stops that happening per page.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${site.name}: ${site.role}`,
};

type OgInput = {
  title: string;
  description: string;
  url: string;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  section?: string;
  tags?: string[];
};

/** Open Graph block with the site-wide defaults already applied. */
export function openGraphFor(input: OgInput): Metadata["openGraph"] {
  return {
    title: `${input.title} | ${site.name}`,
    description: input.description,
    url: input.url,
    siteName: site.name,
    locale: site.locale,
    images: [OG_IMAGE],
    ...(input.type === "article"
      ? {
          type: "article" as const,
          authors: [site.name],
          ...(input.publishedTime ? { publishedTime: input.publishedTime } : {}),
          ...(input.modifiedTime ? { modifiedTime: input.modifiedTime } : {}),
          ...(input.section ? { section: input.section } : {}),
          ...(input.tags ? { tags: input.tags } : {}),
        }
      : { type: "website" as const }),
  };
}

/** Twitter block with the site-wide defaults already applied. */
export function twitterFor(title: string, description: string): Metadata["twitter"] {
  return {
    card: "summary_large_image",
    title,
    description,
    images: [OG_IMAGE.url],
  };
}
