import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Reveal } from "@/components/ui/reveal";
import { Breadcrumbs } from "@/components/ui/breadcrumbs";
import { JsonLd } from "@/components/seo/json-ld";
import { PostBody } from "@/components/blog/post-body";
import { formatPostDate } from "@/components/blog/post-list";
import {
  getPost,
  getRelatedPosts,
  headingId,
  postExcerpt,
  posts,
  postWordCount,
  publishedAt,
} from "@/content/posts";
import { getCategoryMeta } from "@/content/categories";
import { getProject } from "@/content/projects";
import { estimateReadingTime } from "@/lib/reading-time";
import { site } from "@/content/site";
import {
  absoluteUrl,
  BASE_URL,
  breadcrumbSchema,
  graph,
  openGraphFor,
  PERSON_ID,
  WEBSITE_ID,
} from "@/lib/seo";

export function generateStaticParams() {
  return posts.map((p) => ({ slug: p.slug }));
}

type Params = Promise<{ slug: string }>;

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) return {};

  const title = post.seoTitle ?? post.title;
  const description = post.seoDescription ?? post.description;
  // The per-article card generated by ./opengraph-image.tsx.
  const image = `/blog/${post.slug}/opengraph-image`;

  return {
    title,
    description,
    alternates: { canonical: post.canonical ?? `/blog/${post.slug}` },
    authors: [{ name: site.name, url: BASE_URL }],
    openGraph: {
      ...openGraphFor({
        title,
        description,
        url: `/blog/${post.slug}`,
        type: "article",
        publishedTime: publishedAt(post.date),
        modifiedTime: post.updated ? publishedAt(post.updated) : undefined,
        section: post.category,
        tags: post.tags,
      }),
      images: [{ url: image, width: 1200, height: 630, alt: post.title }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
    },
  };
}

export default async function BlogPostPage({ params }: { params: Params }) {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) notFound();

  const related = getRelatedPosts(post);
  const category = getCategoryMeta(post.category);
  const projectsBehind = (post.relatedProjects ?? [])
    .map((s) => getProject(s))
    .filter((p): p is NonNullable<typeof p> => Boolean(p));

  const crumbs = [
    { name: "Home", href: "/" },
    { name: "Blog", href: "/blog" },
    ...(category ? [{ name: category.title, href: `/blog/category/${category.slug}` }] : []),
    { name: post.title, href: `/blog/${post.slug}` },
  ];

  const url = absoluteUrl(`/blog/${post.slug}`);
  const schema = graph(
    {
      "@type": "BlogPosting",
      "@id": url,
      mainEntityOfPage: { "@type": "WebPage", "@id": url },
      url,
      headline: post.title,
      description: post.seoDescription ?? post.description,
      image: [absoluteUrl(`/blog/${post.slug}/opengraph-image`)],
      datePublished: publishedAt(post.date),
      dateModified: publishedAt(post.updated ?? post.date),
      articleSection: post.category,
      keywords: post.tags.join(", "),
      wordCount: postWordCount(post),
      inLanguage: "en-MY",
      author: { "@id": PERSON_ID },
      publisher: { "@id": PERSON_ID },
      isPartOf: { "@id": WEBSITE_ID },
      ...(projectsBehind.length
        ? {
            about: projectsBehind.map((p) => ({
              "@type": "CreativeWork",
              name: p.fullName,
              url: absoluteUrl(`/work/${p.slug}`),
            })),
          }
        : {}),
    },
    breadcrumbSchema(crumbs)
  );

  const showToc = post.sections.length >= 4;

  return (
    <article className="py-16 sm:py-20">
      <JsonLd data={schema} />

      <Container className="max-w-3xl">
        <Breadcrumbs items={crumbs} />

        <Reveal className="mt-8">
          <div className="flex flex-wrap items-center gap-3 text-xs text-text-faint">
            {category ? (
              <Link
                href={`/blog/category/${category.slug}`}
                className="font-mono uppercase tracking-wide text-accent transition-colors hover:text-accent-strong"
              >
                {post.category}
              </Link>
            ) : (
              <span className="font-mono uppercase tracking-wide text-accent">{post.category}</span>
            )}
            <span aria-hidden="true">&middot;</span>
            <time dateTime={post.date}>{formatPostDate(post.date, "long")}</time>
            <span aria-hidden="true">&middot;</span>
            <span>{estimateReadingTime(post.sections)}</span>
          </div>

          <h1 className="mt-4 text-3xl font-semibold tracking-tight text-text text-balance sm:text-4xl">
            {post.title}
          </h1>
          <p className="mt-4 text-lg leading-relaxed text-text-muted">{post.description}</p>

          <p className="mt-5 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-text-faint">
            <span>
              By{" "}
              <Link href="/#about" rel="author" className="text-text-muted transition-colors hover:text-text">
                {site.name}
              </Link>
            </span>
            {post.updated ? (
              <>
                <span aria-hidden="true">&middot;</span>
                <span>
                  Updated <time dateTime={post.updated}>{formatPostDate(post.updated, "long")}</time>
                </span>
              </>
            ) : null}
          </p>
        </Reveal>

        <div className="mt-4 flex flex-wrap gap-2">
          {post.tags.map((tag) => (
            <span
              key={tag}
              className="rounded-full border border-border-strong px-3 py-1 font-mono text-xs text-text-muted"
            >
              {tag}
            </span>
          ))}
        </div>

        {showToc ? (
          <nav aria-label="In this article" className="mt-10 border-l-2 border-border pl-4">
            <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-text-faint">In this article</p>
            <ol className="mt-2 flex flex-col gap-1.5">
              {post.sections.map((section, i) => (
                <li key={section.heading} className="flex gap-3 text-sm">
                  <span className="font-mono text-xs text-text-faint">{String(i + 1).padStart(2, "0")}</span>
                  <a
                    href={`#${headingId(section.heading)}`}
                    className="text-text-muted transition-colors hover:text-text"
                  >
                    {section.heading}
                  </a>
                </li>
              ))}
            </ol>
          </nav>
        ) : null}

        <PostBody sections={post.sections} />

        {projectsBehind.length > 0 ? (
          <Reveal className="mt-14 rounded-lg border border-border-strong bg-bg-elevated p-6">
            <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-faint">
              The work behind this
            </h2>
            <ul className="mt-4 flex flex-col gap-4">
              {projectsBehind.map((p) => (
                <li key={p.slug}>
                  <Link href={`/work/${p.slug}`} className="group inline-flex flex-col gap-1 text-left">
                    <span className="inline-flex items-center gap-1.5 text-sm font-medium text-accent-strong transition-colors group-hover:text-accent">
                      {p.name} case study <ArrowUpRight size={13} />
                    </span>
                    <span className="text-sm leading-relaxed text-text-muted">{p.tagline}</span>
                  </Link>
                </li>
              ))}
            </ul>
          </Reveal>
        ) : null}

        {post.related && post.related.length > 0 ? (
          <Reveal className="mt-6 rounded-lg border border-border bg-bg-elevated p-6">
            <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-faint">Related</h2>
            <ul className="mt-3 flex flex-col gap-2">
              {post.related.map((link) => (
                <li key={link.href}>
                  <Link
                    href={link.href}
                    className="inline-flex items-center gap-1.5 text-sm text-accent-strong transition-colors hover:text-accent"
                  >
                    {link.label} <ArrowUpRight size={13} />
                  </Link>
                </li>
              ))}
            </ul>
          </Reveal>
        ) : null}
      </Container>

      {related.length > 0 ? (
        <Container className="mt-20 max-w-3xl border-t border-border pt-14">
          <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-faint">Keep reading</h2>
          <div className="mt-6 flex flex-col gap-6">
            {related.map((p) => (
              <Link
                key={p.slug}
                href={`/blog/${p.slug}`}
                className="group flex items-center justify-between gap-4 border-b border-border pb-6 last:border-b-0 last:pb-0"
              >
                <div>
                  <h3 className="text-base font-medium text-text">{p.title}</h3>
                  <p className="mt-1 text-sm text-text-muted">{postExcerpt(p)}</p>
                </div>
                <ArrowRight
                  size={16}
                  className="shrink-0 text-text-faint transition-transform duration-200 group-hover:translate-x-1"
                />
              </Link>
            ))}
          </div>
        </Container>
      ) : null}
    </article>
  );
}
